### ISSUE TITLE
Robotron and Joust stuck on "Factory Settings Restored" screen on latest update.

### ISSUE THREAD

**Issue by SegaSnatcher** [MiSTer-devel/Arcade-Robotron_MiSTer#13]
Both games were working fine before the update, now both are stuck at that screen.  

Edit: Found a temp fix, once it shows factory settings restored if you hit reset in the menu it will load the game, but obviously this is not how the core should work.

Edit 2: Another fix is to save settings after "Factory Settings Restored" screen then it will properly boot up to game every time.

**Comment by alanswx** [comment]
We have a fix in the mister binary coming soon. For now save the NVRAM after it says "Factory Settings Restored" by doing "Save settings" in the OSD. It should work on the next boot.

**Comment by wwark** [comment]
Thank you @alanswx and @SegaSnatcher !

@alanswx, is this NVRAM will keep high-score? I managed to have a score above 10000 points on robotron and the high-score is not keep.

**Comment by alanswx** [comment]
Did you hit “save settings” in the osd?

**Comment by wwark** [comment]
Yes i did it.

**Comment by alanswx** [comment]
Is this fixed with the new MiSTer binary?

**Comment by wwark** [comment]
Yes it is fixed ! The high-score is saved (tested with robotron) ! Thanks

**Comment by jlfreund** [comment]
> Did you hit “save settings” in the osd?

Can you clarify?  When stuck in this state, and I exit out to the RetroArch "Quick Menu", I see menu options for "Resume", "Restart", Close Content", etc, as well as "Save State".  Selecting that one, exiting and restarting the game didn't help (still stuck on "Factory Settings Restored".

On the top level "Settings" -> "Saving", I didn't see anything called "Save Settings". 

From the top of RetroArch, do you know where to find it, and what is "osd"?
