### ISSUE TITLE
Robotron video output is not vertically centred on HDMI

### ISSUE THREAD

**Issue by JimmyStones** [MiSTer-devel/Arcade-Robotron_MiSTer#17]
Robotron is offset vertically so there is a gap at the top, and the credits are at the bottom is missing.

Images are from an HBMAME ROM but show the same issue as standard Robotron 2084

[MiSTer with issue](https://cdn.discordapp.com/attachments/806759728885006356/831637592729452545/mister-tiedie.jpg)

[JROK with correct display](https://cdn.discordapp.com/attachments/806759728885006356/831637607153795102/jrok-tiedie.jpg)

**Comment by sorgelig** [comment]
i will check it

**Comment by JimmyStones** [comment]
It looks like alanswx already saw this and has semt me some tips to fix it so if you haven't already started then you can relax :)

**Comment by sorgelig** [comment]
ok

**Comment by JimmyStones** [comment]
Fixed in latest release
