### ISSUE TITLE
Bubbles won't boot with latest .rbf

### ISSUE THREAD

**Issue by mattuna15** [MiSTer-devel/Arcade-Robotron_MiSTer#8]
My Bubbles rom checksums are correct, it gets stuck on initialisation screens. I replaced the rbf and mra files with the equivalent files from here: https://github.com/davewoo999/Arcade-Robotron_MiSTer/tree/master/releases
 as the files were slightly different and it worked fine.

**Comment by sorgelig** [comment]
should be fixed now

**Comment by mattuna15** [comment]
Thank you! I'll test later.

**Comment by mattuna15** [comment]
Tested and working. Thanks
